### ISSUE TITLE
[Feature 3.1] UserDataManager 

### ISSUE THREAD

**Issue by HermesCui** [CSC207-2022F-UofT/course-project-group-140-q-a-forum#5]

**Comment by Teinble** [comment]
Need multiple error message for the SendVerification message. Ordered by priority:
1: Check whether the Username already exists. If exists return "UsernameError"(String)
2: Check whether the Password Valid or No, If not valid return "PasswordValidError"
3. Check whether the Re-enter password match with the password, If no return "ReEnterError"
4: Check whether the typed email is valid or no. If not valid return "EmailError"

If all four above pass, should send the verification code to email and send "SendVerification", Then do the following:
5: Check whether the verification code matches the send verification, If no return "VerificationError"
If matches, send "RegisterSuccess".

**Comment by JY3150** [comment]
User Data Manager corresponds to User controller and we have implemented and tested this!
